### ISSUE TITLE
Trouble during JLutils package installation

### ISSUE THREAD

**Issue by DanyOTRON452** [larmarange/JLutils#10]
I try to install **JLutils package** using **devtools::install_github("larmarange/JLutils")**, but It failed. I work on **R4.1.0**. You can see below the **errors** :

install_github("larmarange/JLutils")
Downloading GitHub repo larmarange/JLutils@HEAD
✓  checking for file ‘/tmp/Rtmpj6wqtb/remotes464f41f80aa9/larmarange-JLutils-24ebeec/DESCRIPTION’ ...
─  preparing ‘JLutils’:
✓  checking DESCRIPTION meta-information ...
─  installing the package to process help pages
         -----------------------------------
─  installing *source* package ‘JLutils’ ...
   ** using staged installation
   ** R
   ** byte-compile and prepare package for lazy loading
   ** help
   *** installing help indices
   *** copying figures
   ** building package indices
   ** testing if installed package can be loaded from temporary location
   Error: le chargement du package ou de l'espace de noms a échoué pour ‘JLutils’ :
   l'objet 'predictdf' est introuvable pendant le chargement de l'espace de noms 'JLutils'
   Erreur : loading failed
   Exécution arrêtée
   ERROR: loading failed
─  removing ‘/tmp/RtmpjbbaM0/Rinst4d603f67d9ba/JLutils’
         -----------------------------------
   ERROR: package installation failed
Erreur : Failed to install 'JLutils' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> ** building package indices
E> ** testing if installed package can be loaded from temporary location
E> Error: le chargement du package ou de l'espace de noms a échoué pour ‘JLutils’ :
E> l'objet 'predictdf' est introuvable pendant le chargement de l'espace de noms 'JLutils'
E> Erreur : loading failed
E> Exécution arrêtée
E> ERROR: loading failed
E> * removing ‘/tmp/RtmpjbbaM0/Rinst4d603f67d9ba/JLutils’
E>       -----------------------------------
E> ERROR: package installation failed

**Comment by larmarange** [comment]
Sorry. This package is unstable and a continuous work in progress. Could you test with the last version? `ggplot2::predictdf()` is now imported.

**Comment by sebleveque** [comment]
Hi Mr  LARMARANGE,

I have similar problem while installing JLutils package from github in R . When I use your command in R I got the following error

>if (!require(devtools)){
+   install.packages('devtools')
+   library(devtools)
+ }
> install_github("larmarange/JLutils")
Downloading GitHub repo larmarange/JLutils@HEAD
Erreur : Failed to install 'JLutils' from GitHub:
  Command failed (1)
De plus : Message d'avis :
Dans system(full, intern = TRUE, ignore.stderr = quiet) :
  l'exécution de la commande ''/usr/bin/git' ls-remote https://git.bioconductor.org/packages/graph RELEASE_3_16 2>/dev/null' renvoie un statut 1

Could you  enlight me on that? If ggplot2::predictdf() is the solution could explain me how to use  it ?

**Comment by larmarange** [comment]
Can you install the package remotes? If you are on Windows, is RTools installed? If not, install it. cf. https://cran.r-project.org/

Please try

`remotes::install_github("larmarange/JLutils")`

**Comment by sebleveque** [comment]
Actually, I  am on MacOS, I intalled  remotes package, however when  I tried  your  command (remotes::install_github("larmarange/JLutils"), I got this error message.


> install.packages("remotes")
essai de l'URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/remotes_2.4.2.tgz'
Content type 'application/x-gzip' length 395393 bytes (386 KB)
==================================================
downloaded 386 KB


The downloaded binary packages are in
      /var/folders/5f/534knqtn3td_m42hw3j2wb780000gn/T//RtmpRxytEY/downloaded_packages
> library(remotes)
> remotes::install_github("larmarange/JLutils")
Downloading GitHub repo ***@***.***
Erreur : Failed to install 'JLutils' from GitHub:
  Command failed (1)
De plus : Message d'avis :
Dans system(full, intern = TRUE, ignore.stderr = quiet) :
  l'exécution de la commande ''/usr/bin/git' ls-remote https://git.bioconductor.org/packages/graph RELEASE_3_16 2>/dev/null' renvoie un statut 1

Sébastien LEVEQUE
Doktorand / PhD Student
Institutionen för ekologi, miljö och geovetenskap / Department of Ecology and Environmental Science
Umeå universitet / Umeå University
SE-901 87 Umeå, Sweden
+46 90 7866961
________________________________
De : Joseph Larmarange ***@***.***>
Envoyé : vendredi 25 novembre 2022 19:16
À : larmarange/JLutils ***@***.***>
Cc : Sébastien Leveque ***@***.***>; Comment ***@***.***>
Objet : Re: [larmarange/JLutils] Trouble during JLutils package installation (#10)


Can you install the package remotes? If you are on Windows, is RTools installed? If not, install it. cf. https://cran.r-project.org/<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcran.r-project.org%2F&data=05%7C01%7C%7C8cb23f63674a44d7457208dacf113dea%7C5a4ba6f9f5314f329467398f19e69de4%7C0%7C0%7C638049970211625564%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8wPmBuD7ZZT2UYj7HDAdMV2vek9zztiIXw2ebSLDxpg%3D&reserved=0>

Please try

remotes::install_github("larmarange/JLutils")

**Comment by larmarange** [comment]
I'm sorry. The error message doesn't explain the issue.

Which function(s) are you interested in?

**Comment by larmarange** [comment]
Maybe you need to install separately the dependencies first, before installing JLutils.

Imports:
    ggplot2 (>= 3.3.0),
    plyr,
    magrittr,
    scales (>= 1.1.0),
    broom (>= 0.5.0),
    dplyr,
    tidyr,
    questionr,
    forcats,
    GGally (>= 2.0.0),
    lifecycle
Suggests:
    gtsummary,
    broom.helpers,
    TraMineR,
    FactoMineR,
    ade4,
    cluster,
    riverplot,
    labelled,
    data.table,
    survey,
    gridExtra,
    tibble,
    msm,
    reshape,
    nnet,
    survival,
    msSurv
