### ISSUE TITLE
Error when using R Markdown for plots which use stat_fill_labels

### ISSUE THREAD

**Issue by nipunaslice** [larmarange/JLutils#6]
I get the following error when I try to render plots which use **stat_fill_labels** function via an R markdown script.

Error in eval(`_inherit`, env, NULL) : object 'StatCount' not found
Calls: <Anonymous> ... fetch_ggproto -> fetch_ggproto -> super -> eval -> eval
Execution halted

**Comment by larmarange** [comment]
Unfortunately, `stat_fill_labels()` does not work anymore with the last version of `ggplot`.

I have proposed a change in `stat_count()` in `ggplot2`: https://github.com/tidyverse/ggplot2/pull/3376/ that will allow to directly compute and display column percentage with `ggplot2` without having the need of `stat_fill_labels()`. However, that proposition was not reviewed yet.

**Comment by larmarange** [comment]
A new and safer solution is now available in dev version of `GGally` which will be released soon: `stat_prop()`
