### ISSUE TITLE
confint.default

### ISSUE THREAD

**Issue by dtdibaba** [larmarange/JLutils#9]
Would you please change the confint to confint.default? 
confint sometimes gives a confidence interval that disagrees with the p-values.

Thank you.
Daniel

**Comment by larmarange** [comment]
Dear @dtdibaba  could you please clarify in which function you are referring to?

Do you have an example?

**Comment by larmarange** [comment]
Is it in tidy_model() ?

It does not seem good to use always confint.default according to https://rstudio-pubs-static.s3.amazonaws.com/33903_d29dd5c31d2048b0a2b51c08394bdbf1.html

However, it is possible to add an option to choose which confidence intervals to compute

**Comment by dtdibaba** [comment]
Yes, it is in the tidy_model() function. When the confidence interval is calculated based on ML rather than Wald method, in rare cases the CI and P-values give different conclusions. I assume confint in R Stats package calculates ML confidence interval.

I was using tab_model() in sjPlot and it uses tidy_model(). Daniel has made some changes now, so it should work.

Thank you!

**Comment by dtdibaba** [comment]
Yes, you are right in tidy_model(). It is used in tab_model() to calculate 95%CI. I think Daniel has made some changes now and it should work.

Thank you!
